export const getInitialCellState = ()=> ({
    description: "",
    updatedAt: null,
    userDisplayName: false,
    botDisplayName: "",
    avatarDir: "",
    backgroundColor: "",
    npc: false,
    encoder: "",
    stateMachine: "",
    decoder: "",
    precision: 0.5,
    retention: 0.8,
    refractory: 4,
    biome: [],
    memory: new Map(),
    script: [],
  });